### ISSUE TITLE
BP项目立项

### ISSUE THREAD

**Issue by juliettezhou** [juliettezhou/writer004-final-BP-project#1]
小伙伴们，今天很激动，我们的团队已经有3位组员了。今天根据阳老师的指导意见，BP的一些相关信息如下：

### 评价标准

- 故事性
- 情感指数
- 生动活泼

### 表现形式类型

- 美图、视频
- 对话
- 科技

### 题材

- 新的商业idea
- 社会公益行动
- 针对现有产品

依据这些标准，前期我们可以批量制造一些项目原型，分别从三个评价标准来细化项目的优势、劣势，欢迎大家贡献idea，并详细描述自己的想法。然后我们筛选出好的项目，分配角色，再看看是不是需要招募新成员。

欢迎大家把自己的项目信息回复在本issue下。

**Comment by Yuwei1030** [comment]
谢谢巧鸽建的仓库和issue。

我先写一下我想到的第一个项目：回家吃饭APP（一直想写人与美食的故事）。

* 简介：【回家吃饭】是国内市场上少有的一款家庭厨房共享平台，可以看做私厨版【饿了么】。平台上的商家不再是餐馆，而是你家附近会做地道家常菜的街坊邻居，大爷大妈。可能是北京的王阿姨，可能是新疆的阿凡提叔叔，也可能是台北的Mike，东西南北，各种口味都很齐全的家乡味。更健康，干净，味道好。每天疲惫奔波的你，回家后，也能吃到一碗热腾腾的家常菜。

* 故事：
人与家乡-->乡情，比如，舌尖上的中国
人与家人-->亲情，比如，小时候妈妈做的红烧牛肉面
人与美食-->治愈，比如，深夜食堂

* 项目优点：
BP的指标来说，这个项目看起来更容易达到。食物是非常有生存进化优势，所以怎么做出来都不会太差。

* 项目缺点：
正因为食物本身具有故事性和情感，讲不好很容易落入俗套，更难让大家感到惊奇和出彩。

我的感觉是，如果做这个项目，做到70分不算难，但做到80-90分会很难。
哈哈一点点想法，大家也可以来说说。我也会再想新项目哈~~

**Comment by Rebecca19** [comment]
谢谢巧鸽！

我先写添几块砖，引引玉。

## 开智部落 IP 孵化|商业

+ 简介：开智部落承载大量优秀潜在 IP ，如能搭建游戏化机制，激励大家不断输出，孵化为各个领域小 IP ，将是一个完整知识 IP 孵化链条。

+ 故事：
     + 英雄之旅 —— 最开始你是一个人在战斗，孤独又容易停滞
     + 部落长跑 —— 你不再是一个人，你可以看到别人的成长与失败，你开始模仿，开始不容易放弃
     + 合作共赢 —— 找到归属感，最后你成为了你自己

+ 项目优点：
    我们有大量实例可操纵，甚至试验；我们可以调研的资源足够多；这个话题可能也是现在比较热与关心的。

+ 项目缺点：
    这个项目偏长期，收益不好计算

其它还有几个，我慢慢列哈。

**Comment by juliettezhou** [comment]
### 老年人生活助理

- 背景：年轻人到大城市奋斗，老人在老家，面对各种复杂的现代生活，力不从心，儿女没有足够的时间、精力解决每一项具体问题。
- 产品：老年人生活助理提供各种服务，比如去银行、手机营业厅办理事务，陪同去医院看病，提供互联网产品的操作指导，帮助老人和子女顺畅的交流，陪聊，阅读，写信等等，是老人身边的得力助手。（这是我近两年在琢磨的真实问题，和真实创业想法。）
- 优势：击中大家痛点，可以获得情感共鸣，可以讲出一个好的故事，比如一位孤独的老人四处碰壁的生活，得到助理帮助后，生活便利，获得自信，给儿女惊喜。


### 儿童辅助阅读

- 背景：现在小孩普遍不喜欢读带文字的书，只爱看图片。
- 产品：还没有想好。
- 优势：儿童教育，解决家长痛点，故事性有待开发。
- 劣势：没有想到好的产品原型。


### 火星开拓者招募

- 背景：Elon Musk的火星飞船已经可以讲人运送到火星，那么人类到火星以后如何生存？如何开拓出新家园？发展星际文明？
- 产品：火星定居点开发产品，有一套方法论和流程，可以帮助新移民建立家园。
- 优势：现代人普遍怕平庸，怕无聊，为勇敢的开拓者们提供一个成为英雄的渠道。最小故事精彩
- 劣势：情感指数低，和大部分人的生活有距离。

**Comment by Rebecca19** [comment]
老年人生活助理看起来很需要哇，我挂票下，开智部落林浩涛他们打算来做，哈哈

**Comment by Rebecca19** [comment]
btw，关于团队分工，两位有什么建议吗，有哪些可能的角色呢？

**Comment by Yuwei1030** [comment]
## 项目定下来后，我们需要完成的工作是：

### 1.文案的撰写
* 草稿框架
* 草稿修改
* 具体内容
### 2.视频的制作
* 素材的收集
* 素材的整理
* 视频合成初稿
* 视频最终版

目前要做的是这些，但是我也不知道如何分工更好，感觉大家每一步都会有不同程度的参与。简单来分的话，文案和视频两大块。感觉我们可以再找一个人，这样的话，两个人主要负责文案，两个人主要负责视频（最好可以招一个视频大神😂）。初步意见，大家一起讨论讨论~~

**Comment by juliettezhou** [comment]
关于项目，**老年人生活助理**，是自己的一个强烈痛点，可能和父母的年龄偏大有关系，看到身边的同事也有类似的苦恼，个人奋斗和父母生活赡养不能兼顾，有些力不从心。从广阔的社会背景来看，这个项目的商业市场需求是巨大的，情感指数也会很高，甚至有可能会变成真正的项目，以我自己目前的资源和经验，还不足以独立创业。 关于**火星招募**，这是一个美好的，近乎理想化的梦想，故事可以很精彩，视频难度很大。

另外，关于我们的**小组分工**，参照其他组的组队情况，角色大致有：
- 产品经理：负责产品规划，品牌故事，视频框架。
- 文案：BP视频的文案撰写
- 设计师：负责视频素材搜集，画面安排，规划视觉效果。
- 技术：负责视频制作、调试。

我自己是项目经理一枚，擅长协调、项目进度把控，极抗压。是Mac小白，可以帮忙收集素材，参与产品规划。不善于讲故事，文笔偏理性，文字情感指数不太高。

**Comment by Yulianxia** [comment]
无意中来到这里，对这个老年人生活助理感受深刻！如果立项，想报名观察员。除了照顾生活，老人更需要的而是精神关怀。印象深刻的一件事，有一次和我妈在儿童广场（德国），我跳上一个双人秋千（以一人一头才能荡起来），让她陪我一起玩，她平时也就是散散步做做操，这次被我逼着上了秋千又踢又蹬，真正的开怀大笑特别开心。我当时就想，能不能发明一种互动器材或运动方式，老人能真正动起来还有互动，兼有趣味。我的母亲67岁。

写的啰嗦了，有点激动。

**Comment by larry8916** [comment]
我也想报名观察员，感觉这个项目能击中人心！
以我为例，我妻子的父母就经常因为现代的电子产品如IPAD和智能手机的使用，经常打电话找我们，慢慢地学会了微信视频聊天，也学会平常用IPAD玩玩麻将，感觉这种老年人助理项目确实有一定的市场。
希望能够出一份力。

**Comment by juliettezhou** [comment]
BP项目已立项，为“老年人生活助理”。很幸运的招募到4位正式组员@Yulianxia@Yuwei1030@Rebecca19@juliettezhou，和3位观察员@Lucy201703@Liuyun16@xunyun。
让我们一起努力，做出优秀的项目吧。
