### ISSUE TITLE
让我们为“银发助理”项目取一个好名字吧

### ISSUE THREAD

**Issue by juliettezhou** [juliettezhou/writer004-final-BP-project#2]
好的名字，承载优秀模因，给我们启发。好名字符合一些规律：
- 进化早期生存优势
- 优秀中华文化模因
- 朗朗上口，好记

今天想到孟子的天下心名句，“老吾老，以及人之老；幼吾幼，以及人之幼。” 如果产品的服务，能做到像对待自己的父母那样耐心、贴心，那么每一对老人就像是多了一些可以依靠的子女，这个意境要比职业化的“助理”更具情感指数和亲近感。 短小、好记的名字，暂时还没有提取出来。

**Comment by Yulianxia** [comment]
巧鸽，除了名字，我们最好有时间节点。5.15路演的话，倒推一个时间表出来。每人分工各有侧重，然后是互相帮忙。确定使用工具（keynote？）沟通会更高效。长三角群的教练凋寒在群里说，名字不要太着急，他们三期团队叫了两周凋寒团队后才确定名字。等我们故事编的感觉到了，名字也会更好贴合的。
是不是开个issue，专门负责技术问题？比如制作方法、颜色选配
再开个issue讨论产品功能。要详细，最后挑选关键几条展示在bp里的，不用考虑可操作性。

目前能想到就这么多。下周三我飞上海呆两天再转南京，加上时差人情孩子和大作业，可能时间不多。先报备，微信会随时在线。
