### ISSUE TITLE
项目总体计划和任务分工

### ISSUE THREAD

**Issue by juliettezhou** [juliettezhou/writer004-final-BP-project#6]
### 项目交付

交付件：demo/幻灯/视频，视频时长 3~5 mins

提交时间：第9周5月12日周五晚19:42 前

路演：第10周5月15～17日晚间，每个项目路演时长 20mins

### 项目安排

第6周：确定产品原型，修改产品最小故事和情节设定，搜集keynote素材，学习keynote制作

第7周：开始制作keynote，并且持续修改

第8周：修改，确定故事终稿。

第9周：keynote转视频，完成制作。

### 角色分工 & 任务领取

| 时间        | 事项                   | 负责人                       | 提交时间         |
| --------- | -------------------- | ------------------------- | ------------ |
| 6wd1~6wd6 | 确定产品原型，写卡片           | 巧鸽，雨莲。其他组员评价，参与讨论         | 6wd6晚上19h42前 |
| 6wd1~6wd6 | 确定最小故事，典型场景，情节设定     | 巧鸽，雨莲。其他组员评价，参与讨论         | 6wd6晚上19h42前 |
| 6wd1~6wd7 | 搜集keynote素材，寻找好的展示模板 | Yuwei, 王彭，小黑。其他组员有余力也可贡献。 | 6wd6晚上19h42前 |
| 6wd1~6wd7 | 学习keynote制作          |                           | 6wd7         |

**Comment by Yuwei1030** [comment]
收到！抱歉最近有点病了，没有参加微信群讨论。如果采用动画制作的话，我给大家推荐一个超级好用的软件，谷歌最新上线的AI画图工具：Autodraw

非常好用，很适合我们小白用户，这是1分43秒宣传视频：http://v.youku.com/v_show/id_XMjcwMjY5NjcxNg==.html?from=s1.8-1-1.2&spm=a2h0k.8191407.0.0
