### ISSUE TITLE
keynote demo展示

### ISSUE THREAD

**Issue by juliettezhou** [juliettezhou/writer004-final-BP-project#9]
接近终版的keynote demo PDF版出炉了，[地址](https://github.com/juliettezhou/writer004-final-BP-project/blob/master/Final%20BP.pdf)

**Comment by guoyuming** [comment]
1. 事件1，老人用产品之前的生活状态，电话里的三件事，没有明确指向困境一个痛点还是三个痛点？如果都说一个问题，三个事件有些重复；如果三个痛点，用户比较难明白是哪三个痛点。一个场景深挖，用户就能理解困境。
2. 产品出现时候，罗列了功能，之后用“买了半年服务”过渡，写使用产品时候的故事，这两个部分可以合并；单纯的罗列功能情感指数不高、容易造成信息负荷，建议直接将功能说明去掉，融入使用产品时发生的故事。
3. 具体到用产品时候的故事，比如“在助理的帮助下, 妈妈学会了给星仔打视频电话”这句（相当于第三方的记录），能不能以星仔或妈妈为焦点，描写如何学会打视频电话，学会之后心情如何，提高情感指数。

**Comment by juliettezhou** [comment]
感谢雨明教练的建议。我思考了一下，总结如下。

1.痛点，只有一个，体现在两方面，P6，儿女想给父母更好的照顾，身处异地无法实现，P7，社会生活太复杂，父母应付起来吃力，又不想总给儿女添麻烦，自己努力去适应。p3-5页，是三个场景，来全方位体现这个痛点。如果给观众看起来痛点不清楚，可以微调表现，强调p6-7

2.第二三组块，其实是产品功能介绍，和使用产品后，父母身上发生的实质改变，更适应和享受现代生活。罗列产品功能是借鉴了Zine 的呈现，借用大脑错误记忆范式，但是实际表现，不如Zine 情感指数高。如果改成产品使用时的场景，画面表现难度大。

3.产品使用后，P18-21，再强化一下心情和感受，呼应前面痛点的解决。

**Comment by juliettezhou** [comment]
后来综合考虑时间和工作量，对于第3点做了调整，提高情感指数。

最终版的keynote demo改为以下： [keynote demo final version](https://github.com/juliettezhou/writer004-final-BP-project/blob/master/BP-assistant.pdf)
